### ISSUE TITLE
error after num_steps = 100000 / 50000000

### ISSUE THREAD

**Issue by zyzhang1130** [TheMTank/ai2thor-experiments#19]
Hi,
I was just directly running the rainbow with all default settings and this error popped out after 100000 steps:

Resetting environment and starting new episode
eval step 200
eval step 400
eval step 600
eval step 800
eval step 1000
Reached maximum episode length: 1000
Traceback (most recent call last):

  File "<ipython-input-1-45e2659a9a6f>", line 1, in <module>
    runfile('/home/user/Documents/Zeyu/cups-rl/main.py', wdir='/home/user/Documents/Zeyu/cups-rl')

  File "/home/user/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "/home/user/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/user/Documents/Zeyu/cups-rl/main.py", line 182, in <module>
    avg_reward, avg_Q = test(env, num_steps, args, dqn, val_mem)

  File "/home/user/Documents/Zeyu/cups-rl/algorithms/rainbow/test.py", line 76, in test
    _plot_line(eval_steps, rewards, 'Reward', path='results')

  File "/home/user/Documents/Zeyu/cups-rl/algorithms/rainbow/test.py", line 112, in _plot_line
    }, filename=os.path.join(path, title + '.html'), auto_open=False)

  File "/home/user/anaconda3/lib/python3.7/site-packages/plotly/offline/offline.py", line 596, in plot
    auto_open=auto_open,

  File "/home/user/anaconda3/lib/python3.7/site-packages/plotly/io/_html.py", line 527, in write_html
    with open(file, "w") as f:

FileNotFoundError: [Errno 2] No such file or directory: 'results/Reward.html'

And yes there is indeed no results/Reward.html in the repo. I wonder do I need to create it myself?

One thing to be noted is that I copied main.py of rainbow to just under cups-rl and ran it, because otherwise lines such as :

from algorithms.rainbow.agent import Agent 

will return error if main.py is under cups-rl/algorithms/rainbow

Thanks for your reply.

**Comment by beduffy** [comment]
I assume the solution is to create a results folder. Plotly creates that html for you to analyse the results but if there is no "results" folder in the same directory or top level (where the python file is being run from) it seems like it can't. 

We'd add a `os.makedirs(filepath)` to the code but we aren't working on this repository anymore unfortunately. If creating the folder doesn't work, let me know.

**Comment by zyzhang1130** [comment]
It worked. Thanks for your advice!
