### ISSUE TITLE
"open_close_interaction": true gives error

### ISSUE THREAD

**Issue by zyzhang1130** [TheMTank/ai2thor-experiments#22]
Hi, when I set "open_close_interaction": true, meaning that i want the agent to be able to open/close openable_objects, it returns me the following error:

Traceback (most recent call last):

  File "<ipython-input-1-45e2659a9a6f>", line 1, in <module>
    runfile('/home/user/Documents/Zeyu/cups-rl/main.py', wdir='/home/user/Documents/Zeyu/cups-rl')

  File "/home/user/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "/home/user/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/user/Documents/Zeyu/cups-rl/main.py", line 142, in <module>
    next_state, _, done, _ = env.step(env.action_space.sample())

  File "/home/user/Documents/Zeyu/cups-rl2/algorithms/rainbow/env.py", line 140, in step
    state, reward, done, info = self.env.step(action)

  File "/home/user/Documents/Zeyu/cups-rl2/gym_ai2thor/envs/ai2thor_env.py", line 175, in step
    obj['distance'] < distance and not obj['isopen'] and \

KeyError: 'isopen'

I tried with a copy of your repo without changing any other things.

**Comment by zyzhang1130** [comment]
Hi, I solved the issue. Somehow the key should be 'isOpen' (with capitalized O). The error occurred in cups-rl/gym_ai2thor/envs/ai2thor_env.py  line 175 and 190.
