### ISSUE TITLE
Error starting AI2THOR Env 

### ISSUE THREAD

**Issue by kaushikb258** [TheMTank/ai2thor-experiments#27]
Unable to start an Env. I tried this: 
python random_walk.py 

/home/kb/anaconda3/lib/python3.6/site-packages/ai2thor/controller.py:1152: UserWarning: start method depreciated. The server started when the Controller was initialized.
  "start method depreciated. The server started when the Controller was initialized."
Traceback (most recent call last):
  File "random_walk.py", line 15, in <module>
    env = AI2ThorEnv(config_dict=config_dict)
  File "/home/kb/CUPS_RL/cups-rl/gym_ai2thor/envs/ai2thor_env.py", line 119, in __init__
    self.controller.start()
  File "/home/kb/anaconda3/lib/python3.6/site-packages/ai2thor/controller.py", line 1163, in start
    self.server.start()
  File "/home/kb/anaconda3/lib/python3.6/site-packages/ai2thor/fifo_server.py", line 203, in start
    os.mkfifo(self.server_pipe_path) 
FileExistsError: [Errno 17] File exists

**Comment by beduffy** [comment]
We made this repo with ai2thor version 0.0.44, a lot has changed with the later versions of ai2thor. Let me know if it works with 0.0.44 or otherwise it might be worth your time trying newer versions like robothor and manipulathor.
